global:
  checkNewVersion: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik

ports:
  web:
    http:
      redirectTo:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    expose:
      default: true

ingressRoute:
  dashboard:
    enabled: true

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addEntryPointsLabels: true

    serviceMonitor:
      enabled: true
      interval: 30s
      namespace: traefik
