apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-shared-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/KevDi/local_app_of_apps.git"
    targetRevision: HEAD
    path: argocd-apps/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
