apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://helm.influxdata.com/"
      chart: influxdb2
      targetRevision: 2.1.2
      helm:
        releaseName: influxdb
        valueFiles:
          - $our-repo/apps-config/influxdb-values.yaml

    - repoURL: "https://github.com/KevDi/local_app_of_apps.git"
      targetRevision: HEAD
      ref: our-repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: influxdb
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jsonPointers:
        - /spec/namespaceSelector
        - /spec/endpoints/0/relabelings
        - /spec/endpoints/0/metricRelabelings
        - /spec/endpoints/0/scheme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
