apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb-metrics
  namespace: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb2
  namespaceSelector:
    matchName:
      - influxdb
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
