apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - traefik.yaml
  - traefik-tls.yaml
  - prometheus-stack.yaml
  - influxdb.yaml
  - influxdb-servicemonitor.yaml
  - grafana-dashboards.yaml
  - root-app.yaml

labels:
  - pairs:
      managed-by: gitops-root
    includeSelectors: false
    includeTemplates: false
