apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - traefik.yaml
  - traefik-tls.yaml
  - prometheus-stack.yaml
  - influxdb.yaml
  - influxdb-servicemonitor.yaml

commonLabels:
  managed-by: gitops-root
